# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
r_packages:
  - testthat
  - covr
r_check_args: --as-cran --run-donttest 
after_success:
  - Rscript -e 'library(covr); codecov()'