// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_numberr_RCPPEXPORTS_H_GEN_
#define RCPP_numberr_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace numberr {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("numberr", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("numberr", "numberr_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in numberr");
            }
        }
    }

    inline NumericVector fibonacci(int n) {
        typedef SEXP(*Ptr_fibonacci)(SEXP);
        static Ptr_fibonacci p_fibonacci = NULL;
        if (p_fibonacci == NULL) {
            validateSignature("NumericVector(*fibonacci)(int)");
            p_fibonacci = (Ptr_fibonacci)R_GetCCallable("numberr", "numberr_fibonacci");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_fibonacci(Rcpp::wrap(n));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_numberr_RCPPEXPORTS_H_GEN_
