

#' Computes the famous \eqn{3n + 1} sequence, also known as the Collatz
#' conjecture.
#' 
#' The Collatz conjecture, also known as the \eqn{3n + 1} problem, is a
#' currently unsolved problem in number theory that is stated as: Start with a
#' positive integer \eqn{n} If \eqn{n} is even, divide \eqn{n} by 2 If \eqn{n}
#' is odd, multiply by 3 and add 1 to obtain \eqn{3n + 1} Repeat this process
#' until the sequence reaches 1
#' 
#' @param n Starting integer to begin \eqn{3n + 1} process
#' @return vector containing sequence generated by the Collatz conjecture. If n
#'   is 1, 1 is returned.
#' @examples 
#' three.n.one(7)
#' three.n.one(10)
#' @references 3x + 1 problem. (2017, May 13). In Wikipedia, The Free
#' Encyclopedia. from
#' https://en.wikipedia.org/w/index.php?title=3x_%2B_1_problem&oldid=780191927 
#' Moler, C. (2011). Numerical computing with MATLAB (1st ed.). Philadelphia,
#' Pa: Society for Industrial & Applied Mathematics.
#' @export
three.n.one <- function(n) {
  if (n == 1) {
    return(n)
  }

  tno.seq <- vector()

  while (n > 1) {
    if (iseven(n)) {
      n <- n / 2
      tno.seq <- append(tno.seq, n)
    }
    else {
      n <- 3 * n + 1
      tno.seq <- append(tno.seq, n)
    }
  }

  return(tno.seq)
}
